Modules/Payroll/Http/routes.php
<?php

use Modules\Payroll\Http\Controllers\HrBonusBatchImportController;

    // Model binding
    Route::model('payrolls', 'Payroll');
    Route::model('deductions', 'Deduction');
    Route::model('hrbonus', 'HrBonus');
    Route::model('userbonu', 'UserBonus');

    Route::bind('payrolls', function($value, $route) {
        return \Modules\Payroll\Entities\PayrollHistory::where('id', $value)->first();
    });

    Route::bind('hrbonus', function ($value, $route){
        return \Modules\Payroll\Entities\HrBonus::where('id', $value)->first();
    });

Route::bind('userbonu', function ($value, $route){
    return \Modules\Payroll\Entities\UserBonus::where('id', $value)->first();
});




Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'extension', 'namespace' => 'Modules\Payroll\Http\Controllers'], function()
{
    Route::resource('payrolls', 'PayrollController');
    Route::post('payroll/{id}/tags', 'PayrollController@tags');

    Route::group([null, 'prefix'=>'payroll'], function (){

        Route::post('run_payroll', 'PayrollController@runPayroll');
        Route::post('export', 'PayrollController@exportPayroll');// manual export
        Route::get('list', 'PayrollController@payrollList');
        Route::get('reports', 'PayrollController@reports');
        Route::delete('deletepayroll', 'PayrollController@deleteItem');
        Route::get('employeesync', 'PayrollController@employeesSync');
        Route::post('employee_date_sync_payroll', 'PayrollController@syncEmployeeToCompany');
        Route::get('employee_export_new', 'PayrollController@exportNewHires');
        Route::resource('deductions', 'DeductionController');
        Route::resource('userdeductions', 'DeductionUserController');
            Route::resource('users.userdeductions', 'DeductionUserController');
        Route::resource('bonus-program', 'BonusProgramController');
        Route::resource('hrbonuses', 'HrBonusController');
        Route::resource('users.userbonus', 'UserBonusController');
        Route::post('import-bonuses', [HrBonusBatchImportController::class, 'importBonus']);

    });

});

Modules/Payroll/Entities/Deduction.php
<?php

namespace Modules\Payroll\Entities;

use Illuminate\Database\Eloquent\Model;

class Deduction extends Model
{
    protected $table = 'ext_payroll_deductions';
    protected $fillable = ['description', 'state', 'pay_code', 'created_by'];
    protected $dates = ['created_at', 'updated_at'];

    public function createdby(){
        return $this->belongsTo('App\User', 'created_by');
    }
}

Modules/Payroll/Entities/DeductionType.php
<?php

namespace Modules\Payroll\Entities;

use Illuminate\Database\Eloquent\Model;

class DeductionType extends Model
{
    protected $table = 'ext_payroll_deduction_types';
    protected $fillable = ['name', 'created_by', 'state'];
}

Modules/Payroll/Http/Controllers/DeductionController.php
<?php

namespace Modules\Payroll\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Payroll\Entities\Deduction;
use Modules\Payroll\Http\Requests\DeductionRequestForm;

class DeductionController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {

        $query = Deduction::query();

        $query->whereIn('state', [0,1])->orderBy('description', 'ASC');
        $items = $query->paginate(config('settings.paging_amount'));

        return view('payroll::deductions.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('payroll::deductions.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(DeductionRequestForm $request)
    {
        $input = $request->all();
        $input['created_by'] = \Auth::user()->id;


        Deduction::create($input);

        return redirect()->route('deductions.index')->with('status', 'Successfully added new item!');

    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show()
    {
        return view('payroll::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit(Deduction $deduction)
    {


        return view('payroll::deductions.edit', compact('deduction'));
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(Request $request, Deduction $deduction)
    {
        $deduction->update($request->all());

        return redirect()->route('deductions.index')->with('status', 'Successfully updated item!');
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy()
    {
    }
}

Modules/Payroll/Resources/views/deductions/create.blade.php
@extends('payroll::layouts.master')


@section('content')

    <ol class="breadcrumb bc-2">
        <li><a href="{{ route('dashboard.index') }}"> <i class="fa fa-folder-open"></i>
                Dashboard
            </a></li>
        <li><a href="{{ route('payrolls.index') }}">Payrolls</a></li>
        <li class="active"><a href="#">New Deduction</a></li>
    </ol>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model(new \Modules\Payroll\Entities\Deduction(), ['route' => ['deductions.store'], 'class'=>'form-horizontal']) !!}

    <div class="row">
        <div class="col-md-6">
            <h3>New Deduction
                <small>Create a new employee deduction.</small>
            </h3>
        </div>
        <div class="col-md-6 text-right" style="padding-top:20px;">
            <a href="{{ route('deductions.index') }}" name="button" class="btn btn-default">Cancel</a>
            {!! Form::submit('Submit', ['class'=>'btn btn-info', 'name'=>'submit']) !!}

        </div>
    </div>

    <hr/>
    <div class="panel panel-primary" data-collapsed="0">
        <div class="panel-heading">
            <div class="panel-title">
                Details
            </div>
            <div class="panel-options"></div>
        </div>
        <div class="panel-body">

            <div class="row">
                <div class="col-md-6">

                    @include('payroll::deductions.partials._form', ['submit_text' => 'Create Bank'])
                </div>
            </div>

        </div>
    </div>
    {!! Form::close() !!}

    @stop

Modules/Payroll/Resources/views/deductions/edit.blade.php
@extends('payroll::layouts.master')

@section('content')

    <ol class="breadcrumb bc-2"> <li> <a href="{{ route('dashboard.index') }}">
                Dashboard
            </a> </li><li ><a href="{{ route('deductions.index') }}">Deductions</a></li>  <li class="active"><a href="#">Edit </a></li></ol>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($deduction, ['method' => 'PATCH', 'route' => ['deductions.update', $deduction->id], 'class'=>'form-horizontal']) !!}

    <div class="row">
        <div class="col-md-6">
            <h3>Edit Deduction <small>{{ $deduction->description }}</small> </h3>
        </div>

        <div class="col-md-6 text-right" style="padding-top:20px;">

            {!! Form::submit('Update', ['class'=>'btn btn-sm btn-info', 'name'=>'submit']) !!}

        </div>

    </div>

    <hr />
    <div class="panel panel-primary" data-collapsed="0">
        <div class="panel-heading">
            <div class="panel-title">
                Details
            </div>
            <div class="panel-options"></div>
        </div>
        <div class="panel-body">

            <div class="row">
                <div class="col-md-6">
                    @include('payroll::deductions.partials._form', ['submit_text' => 'Save'])
                </div>
            </div>


        </div>
    </div>

    {!! Form::close() !!}


    @stop

Modules/Payroll/Resources/views/deductions/index.blade.php
@extends('payroll::layouts.master')

@section('content')

    <ol class="breadcrumb bc-2"> <li> <a href="{{ route('dashboard.index') }}"> <i class="fa fa-folder-open"></i>
                Dashboard
            </a> </li> <li class="active"><a href="{{ route('payrolls.index') }}">Payroll</a></li><li class="active"><a href="#">Deductions</a></li>  </ol>


    <div class="row">
        <div class="col-md-6">
            <h3>Deductions <small>Employees deductions setup.</small> </h3>
        </div>
        <div class="col-md-6 text-right" style="padding-top:15px;">

            <a class="btn btn-sm  btn-success btn-icon icon-left" name="button" href="{{ route('deductions.create') }}" >New Deduction<i class="fa fa-plus"></i></a>


        </div>
    </div>

    <p></p>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary panel-table">
                <div class="panel-heading">
                    <div class="panel-title"><h3>Deductions</h3> <span>.</span></div>
                    <div class="panel-options"> <a href="#" data-rel="reload"><i
                                    class="fa fa-check text-white-1"></i></a>
                        <div class="btn-group" role="group" aria-label="...">


                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-responsive table-striped" id="itemlist">
                        <thead>
                        <tr>
                            <th><input type="checkbox" name="checkAll" value="" id="checkAll"></th>
                            <th>Description</th>
                            <th >Status</th>
                            <th>Created By</th>
                            <th>Date</th>
                            <th class="text-right">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach($items as $item)
                            <tr class="@if($item->state ==0) text-muted @endif">
                              <td></td>
                                <td>{{ $item->description }}</td>
                                <td>
                                    @php
                                    switch ($item->state){
                                        case 1: echo 'Published';break;
                                        case 0: echo 'Unpublished'; break;
                                        case '-2': echo 'Trashed'; break;
                                    }
                                    @endphp
                                </td>
                                <td><a href="{{ $item->createdby->id }}">{{ $item->createdby->name }} {{ $item->createdby->last_name }}</a> </td>
                                <td>{{ $item->created_at->toFormattedDateString() }}</td>
                                <td class="text-right"><a href="{{ route('deductions.edit', $item->id) }}" class="btn btn-sm btn-info">Edit</a></td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            {{ $items->render() }}
        </div>
    </div>

    @stop