routes/web.php
Route::get('import/homecareit/clients', 'ImportController@hcit_clients');
Route::get('import/homecareit/employees', 'ImportController@hcit_employees');
Route::get('import/homecareit/services', 'ImportController@hcit_services');
*/
//Route::resource('users.phones', 'UsersPhoneController');

// Files
Route::post('files/upload', 'FileController@upload');
Route::get('files/download/{filepath}', 'FileController@downloadFile')->middleware('auth');
Route::get('files/view/{filepath}', 'FileController@viewFile')->middleware('auth');

// TODO: Test and rename route functions
Route::get('images/{folder}/{filename}', 'FileController@getImage');
Route::get('file/{folder}/{filename}', 'FileController@getFile');
Route::get('filepath/{path}', 'FileController@dlFile');

// Ringcentral SMS
Route::post('sms/send', 'RingCentralController@sendSms');
Route::post('sms/reply', 'RingCentralController@replySms')->middleware('auth');
Route::get('sms/get', 'RingCentralController@getSms');
Route::get('sms/demo', 'RingCentralController@demo');

Route::get('sms/latenotice', 'RingCentralController@latenotice');// Used for debugging appointments
Route::get('ringcentral/createwebhook/{id}', 'RingCentralController@createWebHook');
Route::post('ringcentral/webhook/login/office/{id}', 'RingCentralController@rcLogin');
Route::post('ringcentral/webhook/logout/office/{id}', 'RingCentralController@rcLogout');
Route::get('ringcentral/getmissedlogins', 'RingCentralController@getMissedLogin');
Route::get('ringcentral/getmissedlogouts', 'RingCentralController@getMissedLogout');
Route::get('ringcentral/createuserwebhook/{user}', 'RingCentralController@createWebhookByUser');
Route::post('ringcentral/webhook/messages/user/{id}', 'RingCentralController@getNewMessage');


Route::resource('jobapplications', 'JobApplicationController');
Route::get('jobapplications/password/reset', 'JobApplicationController@passwordReset');
Route::post('/jobapplications/password/email' , 'JobApplicationController@passwordResetEmail');
Route::get('jobapplications/password/reset/{token}' , 'JobApplicationController@passwordResetLink')->name('jobapplication.password');
Route::post('jobapplication/{id}/tags', 'JobApplicationController@tags');
Route::patch('jobapply/{jobapplications}/update', 'JobApplicationController@patchApplication');
Route::post('jobapply/authenticate', 'JobApplicationController@authenticate');
Route::get('jobapply/list', 'JobApplicationController@listAll');
Route::post('jobapply/convert', 'JobApplicationController@convert');
Route::patch('jobapply/changestatus', 'JobApplicationController@changeStatus');
Route::post('jobapply/upload', 'JobApplicationController@uploadResume');
Route::post('jobapply/addnote', 'JobApplicationController@addNote');

Route::get('jobinquiry', 'JobApplicationController@jobInquiry');
Route::post('jobinquiry-save', 'JobApplicationController@jobInquirySave');
Route::post('jobexport', 'JobApplicationController@exportList');
Route::get('jobinquiry/office/{office}/towns', 'JobApplicationController@getTowns');

Route::get('qbo/oauth', 'QuickBookController@qboOauth');
Route::get('qbo/success', 'QuickBookController@qboSuccess');
// Office/Admin routes only.. change to role:admin|staff
Route::post('appointment/{id}/tags', 'AppointmentController@tags');
Route::group(['prefix' => 'office', 'middleware' => ['auth', 'role:admin|office']], function () {

    Route::resource('dashboard', 'DashboardController');
    Route::post('dashboard-visits', 'DashboardController@getVisits');
    Route::post('dashboard-visit-map', 'DashboardController@getMapData');
    Route::resource('offices', 'OfficeController');
    Route::post('offices/hqcheck', 'OfficeController@HqCheck');
    Route::get('oteam', 'OfficeController@listTeams');

    Route::get('weekly_schedule', 'OfficeController@weeklySchedule');
    Route::get('weekly_schedule_pdf', 'OfficeController@weekly_pdf');

    Route::post('/clients/savesearch' , 'ClientController@saveFilter');
    Route::post('/appointments/savesearch','AppointmentController@saveFilter');
    Route::resource('appointments', 'AppointmentController');
    Route::get('appointment/fetchsummary', 'AppointmentController@fetchSummary');
    Route::get('appointment/resetloginouts', 'AppointmentController@resetLoginouts');
    Route::post('appointment/validaides', 'AppointmentController@validAides');
    Route::post('appointment/{id}/copyvisit', 'AppointmentController@copyVisit');
    Route::post('appointment/checkdayconflict', 'AppointmentController@checkDayConflict');
    Route::post('appointment/changedow', 'AppointmentController@changeDOW');
    Route::get('appointment/resetwages', 'BillingPayrollController@resetWageRates');
    Route::post('appointment/add_differential', 'AppointmentController@addDifferential');
    Route::get('appointment/showloginoutpdf', 'AppointmentController@showLoginOutPDF');
    Route::post('appointment/{appointment}/getEditSchedLayout', 'AppointmentController@getEditSchedLayout');
    Route::post('appointment/{appointment}/editAppointmentFromProfile', 'AppointmentController@editAppointmentFromProfile')->name('editAppointmentFromProfile');
    Route::post('appointment/{appointment}/cancelAppointmentFromProfile', 'AppointmentController@cancelAppointmentFromProfile');
    Route::post('appointment/setpayrollstatus', 'AppointmentController@setPayrollStatus');
    Route::post('appointment/setbillablestatus', 'AppointmentController@setBillableStatus');
    Route::resource('appointments.appointmentnotes', 'AppointmentNoteController');
    Route::get('appointment/{appointment}/getservices', 'AppointmentController@getServices');
    Route::post('appointment/changeservice', 'AppointmentController@changeService');
    Route::post('appointment/{appointment}/splitvisit', 'AppointmentController@splitVisit');
    Route::post("appointment/export/change_log" , "AppointmentController@assignment_change_log")->name("assignment_change_log");
    //Route::get('appointment/debug', 'AppointmentController@debug');

    Route::post('updateappointments', 'AppointmentController@updateAppointments');
    Route::post('checkconflicts', 'AppointmentController@checkConflicts')->name('appointment-vs-aide-conflicts');
    Route::post('updateAppointmentPrice', 'AppointmentController@updateAppointmentPrice');
    Route::post('createReport', 'AppointmentController@createReport');
    Route::post('openvisit', 'AppointmentController@openVisit');
    Route::post('saveopenvisit', 'AppointmentController@saveOpenVisit');
    Route::post('findAppointmentsByDate', 'AppointmentController@findAppointmentsByDate');
    Route::resource('clients', 'ClientController');
    Route::post('client/convert', 'ClientController@convert');
    Route::delete('client/trash', 'ClientController@trash');
    Route::get('client/ajaxsearch', 'ClientController@ajaxSearch');
    Route::get('client/ajaxsearchall', 'ClientController@ajaxSearchAll');
    Route::post('clients/exportlist', 'ClientController@exportList');
    Route::get('client/listpricesbypayer', 'ClientController@listPricesByPayer');
    Route::post('openvisits/batchsms', 'AppointmentController@sendBatchOpenVisitSMS');
    Route::get('client/{users}/sched-change-tmpl', 'ClientController@emailChangeForm');
    Route::post('client/{users}/edit-appointment-email-form', 'ClientController@appointmentEditEmailForm');


    Route::resource('clientpricings', 'ClientPricingController');
    Route::resource('clients.clientpricings', 'ClientPricingController');

    Route::resource('orders', 'OrderController');
    Route::get('order/extendapproved', 'OrderController@extendApprovedAssignments');
    Route::post('order/markready', 'OrderController@markAssignmentReady');
    Route::post('order/{user}/generateall', 'OrderController@generateAllAssignments');
    Route::resource('clients.orders', 'OrderController');//sub resource
    Route::resource('orderspecs', 'OrderSpecController');
    Route::resource('clients.orders.orderspecs', 'OrderSpecController');
    Route::post('orderspec/validaides', 'OrderSpecController@validAides');
    Route::resource('prices', 'PriceController');
    Route::get('generateappointments', 'OrderController@generate_appointments');
    Route::post('extendorders', 'OrderController@extendOrder');
    Route::post('client/{user}/createorderassignment', 'OrderController@createOrderAssignment');
    Route::resource('orderspecassignments', 'OrderSpecAssignmentController');
    Route::resource('clients.orders.orderspecs.orderspecassignments', 'OrderSpecAssignmentController');
    Route::post('orderspecassignment/{orderspecassignments}/resume', 'OrderSpecAssignmentController@resumeAssignment');
    Route::get('matchcustomerqb', 'ClientController@matchCustomerQBAccount');
    Route::get('fetchqbosubaccounts', 'ClientController@fetchQBOSubAccountAndClients');
    Route::post('manualimportqbsubaccounts', 'ClientController@manualImportQBSubAccounts');
    Route::post('exportclientcontacts', 'ClientController@exportClientContacts');
    Route::get('cancelvisittmpl', 'ClientController@cancelVisitTmpl');


    Route::post('manualimportqb/{organization}/{user}', 'ClientController@manualImportQBAccount');

    Route::post('orderspecassignment/{orderspecassignments}/{user}/activeauth', 'OrderSpecAssignmentController@activeAuthorization');

    Route::get('orderspecassignment/{id}/checklastbusinessactivity', 'OrderSpecAssignmentController@checkLastBusinessActivity');
    Route::resource('pricelists', 'PriceListController');
    Route::post('pricelist/copy/{id}', 'PriceListController@copyPricelist');
    Route::get('pricelist/ajaxsearch', 'PriceListController@ajaxSearch');
    Route::get('pricelist/{pricelist}/fetchprices', 'PriceListController@fetchPrices');


    Route::resource('servicelines', 'ServiceLineController');
    Route::resource('serviceofferings', 'ServiceOfferingController');
    Route::resource('serviceoffering/{id}/tasks', 'ServiceOfferingController@getTasks');

resources/views/dashboard/aideinsight.blade.php
@extends('layouts.dashboard')


@section('sidebar')
    <div style="margin-left: 15px; margin-right: 15px; color: #aaabae;" id="sidediv" class=" main-menu">
        <ul id="main-menu" class="main-menu">
        <li class="root-level"><a href="{{ route('dashboard.index') }}">
                <div class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x text-darkblue-2"></i>
                    <i class="fa fa-dashboard fa-stack-1x text-primary"></i>
                </div> <span
                        class="title">Dashboard</span></a>
        </li>
        </ul>

<div class="row">
    <div class="col-md-12">

         <div class="tile-stats tile-gray"> <div class="icon"><i class="entypo-paper-plane"></i></div> <div class="num">
             ${{ number_format($totalPayroll) }}</div> <h3>Earned</h3> <p><span class="bar" style="display: none;">{{ $payrollAmount }}</span><canvas class="peity" height="32" width="300" style="height: 16px; width: 150px;"></canvas></p> </div>
    </div>

</div>

    </div>
@endsection



@section('content')
    <ol class="breadcrumb bc-3">
        <li class="active"><a href="{{ route('dashboard.index') }}"> <i class="fa fa-folder-open"></i>
                Dashboard
            </a></li>
    </ol>
<h2>{{ $user->name }} {{ $user->last_name }} Insight <small>Gain an understanding of the Aide's progress.</small></h2>
    <div class="row top-summary">
        <div class="col-lg-2 col-md-2">
            <div class="widget darkblue-2">
                <div class="widget-content padding">
                    <div class="widget-icon">

                    </div>
                    <div class="text-box">
                        <p class="maindata">Desired <b>HOURS</b></p>
                        <h2><span class="animate-number" data-value="{{ $percentsched }}" data-duration="3000">{{ $percentsched }}%</span></h2>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="widget-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <i class="fa fa-clock-o rel-change"></i> {{ number_format(round($total_sched_hours)) }} scheduled
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <div class="widget orange-4">
                <div class="widget-content padding">
                    <div class="widget-icon">

                    </div>
                    <div class="text-box">
                        <p class="maindata">Gross <b>PROFIT</b></p>
                        <h2><span class="animate-number" data-value="{{ $grossProfit }}" data-duration="3000">{{ $grossProfit }}%</span></h2>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="widget-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            Target 47.50%
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <div class="widget green-2">
                <div class="widget-content padding">
                    <div class="widget-icon">

                    </div>
                    <div class="text-box">
                        <p class="maindata">GREEN <b></b></p>
                        <h2><span class="" data-value="{{ $percentGreen }}" data-duration="1000">{{ $percentGreen }}%</span></h2>

                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="widget-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            Target 40%
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>



        <div class="col-lg-2 col-md-2">
            <div class="widget orange-4">
                <div class="widget-content padding">
                    <div class="widget-icon">

                    </div>
                    <div class="text-box">
                        <p class="maindata">YELLOW <b></b></p>
                        <h2><span class="animate-number" data-value="{{ $percentYellow }}" data-duration="3000">{{ $percentYellow }}%</span></h2>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="widget-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            Target 10%
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>

        <div class="col-lg-2 col-md-2">
            <div class="widget red-1">
                <div class="widget-content padding">
                    <div class="widget-icon">

                    </div>
                    <div class="text-box">
                        <p class="maindata">RED <b></b></p>
                        <h2><span class="animate-number" data-value="{{ $percentRed }}" data-duration="3000">{{ $percentRed }}%</span></h2>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="widget-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            Target 5%
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-2 col-md-2">
            <div class="widget blue-2">
                <div class="widget-content padding">
                    <div class="widget-icon">

                    </div>
                    <div class="text-box">
                        <p class="maindata">BLUE <b></b></p>
                        <h2><span class="animate-number" data-value="{{ $percentBlue }}" data-duration="3000">{{ $percentBlue }}%</span></h2>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="widget-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            Target 10%
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>

    </div>

    <div class="panel-body with-table no-padding no-margin"><table class="table table-bordered"> <tbody> <tr> <td width="50%"> <strong>Year {{ \Carbon\Carbon::now()->year }} Quarterly Schedule</strong> <br> <div id="chart3" style="height: 250px"> </div> </td> <td> <strong>Last 5 Weeks Trending Metrics</strong> <br> <div id="chart4" style="height: 250px"></div> </td> </tr> </tbody> </table></div>


    <div class="panel-body with-table no-padding no-margin"><table class="table table-bordered"> <tbody> <tr> <td width="33%"> <strong>On Time</strong> - past 12 months <br> <div id="chart5" style="height: 250px;"></div> </td> <td width="33%"> <strong>Duration</strong> - past 12 months <br> <div id="chart6" style="height: 250px"></div> </td> <td width="33%"> <strong>Sick/Vacation</strong> - past 12 months <br> <div id="chart7" style="height: 250px"></div> </td> </tr> </tbody> </table></div>

    <div class="row">
        <div class="col-md-7">
            <div class="panel panel-primary"> <div class="panel-heading"> <div class="panel-title"><strong>Aide Data</strong> - past 12 months</div> <div class="panel-options"> <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a> <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a> <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a> <a href="#" data-rel="close"><i class="entypo-cancel"></i></a> </div> </div> <div class="panel-body with-table"><table class="table table-bordered"> <thead> <tr> <th width="15%">Graph</th> <th>Data Type</th> <th width="30%">Total</th> </tr> </thead> <tbody>  <tr> <td> <span class="line" style="display: none;">{{ $visits }}</span><canvas class="peity" height="32" width="300" style="height: 16px; width: 150px;"></canvas> </td> <td>
                                Visits
                            </td> <td>
                {{ number_format($toalvisits) }}
                            </td> </tr> <tr> <td> <span class="bar" style="display: none;">{{ $durationamounts }}</span><canvas class="peity" height="32" width="300" style="height: 16px; width: 150px;"></canvas> </td> <td>
                                Duration
                            </td> <td>
                {{ number_format($durationtotal) }} hrs
                            </td> </tr><tr> <td> <span class="line" style="display: none;">{{ $sickamounts }}</span><canvas class="peity" height="32" width="300" style="height: 16px; width: 150px;"></canvas> </td> <td>
                                Sick
                            </td> <td>
                {{ number_format($sickvisits) }}
                            </td> </tr> <tr> <td> <span class="bar" style="display: none;">{{ $noshowamounts }}</span><canvas class="peity" height="32" width="300" style="height: 16px; width: 150px;"></canvas> </td> <td>No Show</td> <td>{{ number_format($noshowvisits) }}</td> </tr>  <tr> <td> <span class="bar" style="display: none;">{{ $milesamount }}</span><canvas class="peity" height="50" width="300" style="height: 25px; width: 150px;"></canvas> </td> <td>
                                Miles
                            </td> <td>
                {{ number_format($milestotal) }}
                            </td> </tr> </tbody> </table></div> </div>
        </div>
        <div class="col-md-5">
            <div class="panel panel-primary"> <div class="panel-heading"> <div class="panel-title"><strong>Payroll</strong> - past 12 months</div> <div class="panel-options"> <a href="#sample-modal" data-toggle="modal" data-target="#sample-modal-dialog-1" class="bg"><i class="entypo-cog"></i></a> <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a> <a href="#" data-rel="reload"><i class="entypo-arrows-ccw"></i></a> <a href="#" data-rel="close"><i class="entypo-cancel"></i></a> </div> </div> <div class="panel-body"><div id="chart9" ></div> </div>  </div>
        </div>
    </div>
    <script>
        jQuery(document).ready(function($) {


            if (typeof Morris != 'undefined') {

                // Bar Charts
                Morris.Bar({
                    element: 'chart3',
                    axes: true,
                    data: {!! $quarterly_visits !!},
                    xkey: 'quarter',
                    ykeys: ['visitcount', 'durationsum', 'actualdurationsum'],
                    labels: ['Visits', 'Schedule Duration', 'Actual Duration'],
                    barColors: ['#707f9b', '#455064', '#242d3c']

                });

                // Bar Charts
                Morris.Bar({
                    element: 'chart4',
                    axes: true,
                    data: {!! $metricTrend !!},
                    xkey: 'week',
                    ykeys: ['countBlue', 'countRed', 'countYellow', 'countGreen'],
                    labels: ['Blue', 'Red', 'Yellow', 'Green'],
                    barColors: ['#3498db', '#eb5055', '#edce8c', '#9ec789']


                });

                // Payroll bar chart
                Morris.Bar({
                    element: 'chart9',
                    axes: true,
                    data: {!! $payrollStats !!},
                    xkey: 'month',
                    ykeys: ['totalamt'],
                    labels: ['Total'],
                    barColors: ['#9ec789']


                });

                // Donut
                Morris.Donut({
                    element: 'chart5',
                    data: {!! $onTimeMetric !!},
                    colors: ['#00a651', '#00bff3', '#eb5055']
                });

                Morris.Donut({
                    element: 'chart6',
                    data: {!! $durationMetric !!},
                    colors: ['#eb5055', '#707f9b', '#eb5055']
                })

                Morris.Donut({
                    element: 'chart7',
                    data: {!! $statusMetric !!},
                    colors: ['#f26c4f', '#0072bc', '#eb5055']
                })


            }

            // Peity Graphs
            if($.isFunction($.fn.peity))
            {
                $("span.pie").peity("pie", {colours: ['#0e8bcb', '#57b400'], width: 150, height: 25});
                $("span.line").peity("line", {width: 150});
                $("span.bar").peity("bar", {width: 150});

            }
        });

        function getRandomInt(min, max)
        {
            return Math.floor(Math.random() * (max - min + 1)) + min;
        }
    </script>
@stop

resources/views/dashboard/index.blade.php
@extends('layouts.dashboard')


@section('content')



    <ol class="breadcrumb bc-3">
        <li class="active"><a href="{{ route('dashboard.index') }}"> <i class="fa fa-folder-open"></i>
                Dashboard
            </a></li>
    </ol>

    @role('admin')
        @include('dashboard/partials/_admin', [])
    @else
        @include('dashboard/partials/_office', [])
    @endrole


@endsection

resources/views/dashboard/show.blade.php
This is the user page